parameters:
    akeneo_spreadsheet_parser.xlsx.archive.class:                   Akeneo\Component\SpreadsheetParser\Xlsx\Archive
    akeneo_spreadsheet_parser.xlsx.archive_loader.class:            Akeneo\Component\SpreadsheetParser\Xlsx\ArchiveLoader
    akeneo_spreadsheet_parser.xlsx.shared_strings.class:            Akeneo\Component\SpreadsheetParser\Xlsx\SharedStrings
    akeneo_spreadsheet_parser.xlsx.shared_strings_loader.class:     Akeneo\Component\SpreadsheetParser\Xlsx\SharedStringsLoader
    akeneo_spreadsheet_parser.xlsx.relationships.class:             Akeneo\Component\SpreadsheetParser\Xlsx\Relationships
    akeneo_spreadsheet_parser.xlsx.relationships_loader.class:      Akeneo\Component\SpreadsheetParser\Xlsx\RelationshipsLoader
    akeneo_spreadsheet_parser.xlsx.styles.class:                    Akeneo\Component\SpreadsheetParser\Xlsx\Styles
    akeneo_spreadsheet_parser.xlsx.styles_loader.class:             Akeneo\Component\SpreadsheetParser\Xlsx\StylesLoader
    akeneo_spreadsheet_parser.xlsx.worksheet_list_reader.class:     Akeneo\Component\SpreadsheetParser\Xlsx\WorksheetListReader
    akeneo_spreadsheet_parser.xlsx.row_iterator.class:              Akeneo\Component\SpreadsheetParser\Xlsx\RowIterator
    akeneo_spreadsheet_parser.xlsx.row_iterator_factory.class:      Akeneo\Component\SpreadsheetParser\Xlsx\RowIteratorFactory
    akeneo_spreadsheet_parser.xlsx.value_transformer.class:         Akeneo\Component\SpreadsheetParser\Xlsx\ValueTransformer
    akeneo_spreadsheet_parser.xlsx.value_transformer_factory.class: Akeneo\Component\SpreadsheetParser\Xlsx\ValueTransformerFactory
    akeneo_spreadsheet_parser.xlsx.date_transformer.class:          Akeneo\Component\SpreadsheetParser\Xlsx\DateTransformer
    akeneo_spreadsheet_parser.xlsx.spreadsheet.class:               Akeneo\Component\SpreadsheetParser\Xlsx\Spreadsheet
    akeneo_spreadsheet_parser.xlsx.spreadsheet_loader.class:        Akeneo\Component\SpreadsheetParser\Xlsx\SpreadsheetLoader
    akeneo_spreadsheet_parser.xlsx.column_index_transformer.class:  Akeneo\Component\SpreadsheetParser\Xlsx\ColumnIndexTransformer
    akeneo_spreadsheet_parser.xlsx.row_builder.class:               Akeneo\Component\SpreadsheetParser\Xlsx\RowBuilder
    akeneo_spreadsheet_parser.xlsx.row_builder_factory.class:       Akeneo\Component\SpreadsheetParser\Xlsx\RowBuilderFactory

services:
    akeneo_spreadsheet_parser.xlsx.archive_loader:
        class: %akeneo_spreadsheet_parser.xlsx.archive_loader.class%
        public: false
        arguments:
            - %akeneo_spreadsheet_parser.xlsx.archive.class%

    akeneo_spreadsheet_parser.xlsx.shared_strings_loader:
        class: %akeneo_spreadsheet_parser.xlsx.shared_strings_loader.class%
        arguments:
            - %akeneo_spreadsheet_parser.xlsx.shared_strings.class%

    akeneo_spreadsheet_parser.xlsx.relationships_loader:
        class: %akeneo_spreadsheet_parser.xlsx.relationships_loader.class%
        arguments:
            - %akeneo_spreadsheet_parser.xlsx.relationships.class%

    akeneo_spreadsheet_parser.xlsx.styles_loader:
        class: %akeneo_spreadsheet_parser.xlsx.styles_loader.class%
        arguments:
            - %akeneo_spreadsheet_parser.xlsx.styles.class%

    akeneo_spreadsheet_parser.xlsx.worksheet_list_reader:
        class: %akeneo_spreadsheet_parser.xlsx.worksheet_list_reader.class%

    akeneo_spreadsheet_parser.xlsx.date_transformer:
        class: %akeneo_spreadsheet_parser.xlsx.date_transformer.class%

    akeneo_spreadsheet_parser.xlsx.column_index_transformer:
        class: %akeneo_spreadsheet_parser.xlsx.column_index_transformer.class%

    akeneo_spreadsheet_parser.xlsx.value_transformer_factory:
        class: %akeneo_spreadsheet_parser.xlsx.value_transformer_factory.class%
        arguments:
            - @akeneo_spreadsheet_parser.xlsx.date_transformer
            - %akeneo_spreadsheet_parser.xlsx.value_transformer.class%

    akeneo_spreadsheet_parser.xlsx.row_builder_factory:
        class: %akeneo_spreadsheet_parser.xlsx.row_builder_factory.class%
        arguments:
            - %akeneo_spreadsheet_parser.xlsx.row_builder.class%

    akeneo_spreadsheet_parser.xlsx.row_iterator_factory:
        class: %akeneo_spreadsheet_parser.xlsx.row_iterator_factory.class%
        arguments:
            - @akeneo_spreadsheet_parser.xlsx.row_builder_factory
            - @akeneo_spreadsheet_parser.xlsx.column_index_transformer
            - %akeneo_spreadsheet_parser.xlsx.row_iterator.class%

    akeneo_spreadsheet_parser.xlsx.spreadsheet_loader:
        class: %akeneo_spreadsheet_parser.xlsx.spreadsheet_loader.class%
        arguments:
            - @akeneo_spreadsheet_parser.xlsx.archive_loader
            - @akeneo_spreadsheet_parser.xlsx.relationships_loader
            - @akeneo_spreadsheet_parser.xlsx.shared_strings_loader
            - @akeneo_spreadsheet_parser.xlsx.styles_loader
            - @akeneo_spreadsheet_parser.xlsx.worksheet_list_reader
            - @akeneo_spreadsheet_parser.xlsx.value_transformer_factory
            - @akeneo_spreadsheet_parser.xlsx.row_iterator_factory
            - %akeneo_spreadsheet_parser.xlsx.spreadsheet.class%
        tags:
            - { name: akeneo_spreadsheet_parser.spreadsheet_loader, alias: xlsx }